name: parkour_app
description: An App that helps people track the nearest parkour training centers

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 4.0.1
  shared_preferences: 0.5.6+3
  package_info: 0.4.0+16
  flutter_localizations:
    sdk: flutter
  auto_route: 0.2.2
  load: 0.1.5+1
  http_logger: 1.0.0
  connectivity: 0.4.8+2
  rxdart: 0.22.6
  json_annotation: 3.0.0
  flutter_image_compress: 0.6.5
  image_picker: 0.6.4
  path: 1.6.4
  email_validator: 1.0.4
  google_sign_in: 4.1.1
  #flutter_facebook_login: 3.0.0
  firebase_auth: 0.16.0
  firebase_database: 3.1.3
  dotted_border: 1.0.5
  path_provider: 1.6.5
  firebase_storage: 3.1.5





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 3.2.4
  auto_route_generator: 0.2.2
  build_runner: 1.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - assets/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
